spring:
  datasource:
    url: jdbc:mysql://{}:3306/board?serverTimezone=UTC&useSSL=false
    username: {}
    password: {}
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: {}
      port: 6379


  route:
    front: http://ktb-rian.com:80

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: {}
            client-secret: {}
            redirect-uri: "http://ktb-rian.com:80/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - nickname
              - email
          kakao:
            client-name: kakao
            client-id: {}
            redirect-uri: "http://ktb-rian.com:80/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: response
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: id

aws:
  region: ap-northeast-2
  access_key: {}
  secret_key: {}
  bucket: {}
  cloud_front:
    domain: {}
    default-profile-image-key: "default-profile.png" # s3에 올려둔 기본 이미지 경로

jwt:
  secret: {}
