spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379


  route:
    front: ${ROUTE_FRONT}


aws:
  region: ${S3_REGION}
  access_key: ${S3_ACCESS_KEY}
  secret_key: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET}
  cloud_front:
    domain: ${CLOUDFRONT_DOMAIN}
    default-profile-image-key: "default-profile.png" # s3에 올려둔 기본 이미지 경로

jwt:
  secret: ${JWT_SECRET}
